[backend_rules]
image = "awww"
gif = "awww"
video = "mpvpaper"

[backend_fallbacks]
awww = ["swww"]
swww = []
hyprpaper = []
mpvpaper = []
gslapper = []

[backends.awww]
command = "awww"
transition_type = "grow"
transition_duration = 0.8
transition_fps = 60
